PR to implement issue #2.
lfurzewaddock/vscode-opn pull request #5
Opened 2016-09-08 22:42 UTC by hashhar

This commit adds a context menu entry to the explorer and an associated
command to open the file (which was clicked on) in an external program.

The external program can be configured using the extension's
configuration under the key `externalEditor`. The key can accept full
paths to the tools or just the name of the program if it is present in
PATH. Arguments to be passed to the program can also be specified in the
accompanying configuration under the key `externalEditorArgs`.

Example configuration:
```
"vscode-opn.externalEditor": "emacs",
"vscode-opn.externalEditorArgs": [
    "+10",
    "-nbc"
]
```

2016-09-08 22:45 UTC, hashhar commented
I think the linter is having some issues.

I have tested this code very rigorously to make sure that it never fails ungracefully.

I took care of:
1. If the click did not happen on a file.
2. If the config file has issues with the two new keys.

2016-09-16 23:33 UTC, hashhar commented
@lfurzewaddock Just wanted to remind you that I have submitted a PR.

2016-09-19 14:18 UTC, lfurzewaddock commented
Apologies @hashhar, I've been away on holiday. Please give me few days to catch up.

2016-09-21 17:43 UTC, lfurzewaddock commented
Before I go through any code, I'd like to check what the intended behaviour is. When using your 'Open file...' context menu, is it only possible to set a single program/editor to handle all languages, (therefore file types)?

If so, this doesn't fit well with the existing functionality. Would it be possible to use the existing optional settings per language [JSON (vscode-opn.perLang)](https://github.com/lfurzewaddock/vscode-opn#customise-behaviour-per-language-optional), which set both the program/editor and additional arguments to send to the program/editor per language? Also, as these settings are optional, if there are no settings for the relevant language set, the OS default program/editor should open.

2016-09-21 17:46 UTC, hashhar commented
Currently I have added a configuration setting called `externalEditor` which is used for all programs.
I think what you're suggesting is better but it can be improved further if we use the language specific settings if they are present and use the `externalEditor` otherwise. If `externalEditor` is also blank, we use the OS defaults.

If you like this approach I can implement it and send you a PR. But it may take some time as my campus placements are on right now and will be until this Saturday.

2016-09-21 19:05 UTC, lfurzewaddock commented
I can see why you might want a 'super' program/editor to handle various languages, without explicitly setting the same editor for several languages, so how about adding 'defaultAll' as a pseudo language option to JSON (vscode-opn.perLang) which could act as a fall through 'catch all' option?

That way related settings are in the same place and the feature is easier to communicate to users.

I'm OK to wait, I can only fit this around other things too.

2016-09-21 19:07 UTC, hashhar commented
Could you explain what you meant by defaultAll with an example JSON config?

2016-09-21 19:30 UTC, lfurzewaddock commented
See below the original example in the docs with a 3rd option added to the `opnOptions` array. Notice the extra optional options;

- `isUseWebServer` to open file on a local webserver 
- `isUseFsPath` to force use of file system path over URI path
- `isWaitForAppExit` is a specific argument passed to the Node module dependency [opn](https://github.com/sindresorhus/opn)

```    

"vscode-opn.perLang": {
    "opnOptions": [
      {
        "forLang": "html",
        "openInApp": "chrome",
        "openInAppArgs": ["--incognito"],
        "isUseWebServer": true,
        "isUseFsPath": false,
        "isWaitForAppExit": true
      },
      {
        "forLang": "plaintext",
        "openInApp": "notepad++",
        "openInAppArgs": [],
        "isUseWebServer": false,
        "isUseFsPath": true,
        "isWaitForAppExit": true
      },
      {
        "forLang": "defaultAll",
        "openInApp": "emacs",
        "openInAppArgs": ["+10", "-nbc"],
        "isUseWebServer": false,
        "isUseFsPath": false,
        "isWaitForAppExit": true
      }
    ]
  },
  "vscode-opn.webServerProtocol": "http",
  "vscode-opn.webServerHostname": "localhost",
  "vscode-opn.webServerPort": 8080

```

2016-12-23 19:20 UTC, hashhar commented
@lfurzewaddock I finally got the time to do this. I added a pseudo-language id called `default` which can be used to set options for unconfigured languages. I still have to test it I guess.

I also got around to updating the dependencies and targeting vscode 1.0.

2017-01-24 16:50 UTC, hashhar commented
@lfurzewaddock Just checking in to remind you about this.

2017-01-24 19:30 UTC, lfurzewaddock commented
Hi @hashhar, sorry for the delay.

I ran your version locally in debug mode, leaving the default settings and an error is raised when I right click a file and choose option "Open in External Editor".

> Windows cannot find 'null'. Make sure you've typed the name correctly, then try again.

 I'm guessing this is related to the  "vscode-opn.externalEditor" default setting.

2017-01-24 19:35 UTC, lfurzewaddock reviewed
Is this code duplication required? Why is it not possible to modify the existing function 'disposable' so you can call that from the menu explorer/context command?

2017-01-24 19:44 UTC, lfurzewaddock commented
This is JavaScript Repo, currently using ES5. Please do not include any 'TypeScript' dependencies/cruft.

@hashhar, I think I should implement your solution as it's a good/useful feature. If I do I will give you credit.

2017-01-24 19:56 UTC, hashhar commented
@lfurzewaddock Ok, I see what happenned. I did not implement this fully. And was new to VSCode at the time when I started working on this. I can send you a clean ES5 update to this PR sometime by tomorrow night. Or you can implement it yourself if you want.

2017-01-24 20:23 UTC, lfurzewaddock commented
@hashhar, if you want to submit another PR, I'll review it, but I'd like to see a minimal set of changes so it is easy for me to review and accept.

2017-01-26 00:51 UTC, hashhar commented
@lfurzewaddock Done. This adds a new pseudo language identifier like we discussed above. **Unfortunately I couldn't figure out how to add a default value for it or add a schema to validate it.**

This also adds a context menu entry to both the editor and the file explorer for the command.

If no language specific configuration is provided then we fall back to the OS defaults.

2017-02-22 14:25 UTC, hashhar commented
@lfurzewaddock Should I update the dependencies too to get rid of the BitHound errors.

2017-02-22 19:31 UTC, lfurzewaddock commented
@hashhar, no need. I'm going to make quite a few changes soon.

2017-02-25 16:23 UTC, lfurzewaddock requested changes
Unexpected Behaviour

If I right click on a file a context menu opens for that file. From this context menu when 'Open' is clicked, I would expect the file which had been selected by the the right click to open rather the current active file in the editor.

Please remove your changes from the file 'extension.js' and 'jsconfig.json' and resubmit your pull request so I can merge it.

2017-03-02 10:02 UTC, hashhar commented
I'll get working on this. Sorry I saw this so late.

2018-11-14 12:42 UTC, closed without merging